### ISSUE TITLE
Filter for Pickups and Weapons ?

### ISSUE THREAD

**Issue by Punjara** [assaultcube/AC#330] opened 2021-05-10 14:37 UTC
Is there a possibility to filter out pickups or weapons to make custom match, like filter out akimbo or smg only match or no armor match...? if it possible then make a filter command for it or menu option...

**Comment by drian0** [comment] 2021-05-11 06:26
No, this is currently not possible.

Configuring a custom game mode is most likely too complicated and therefore confuses people.

The way this would be done normally is via an additional game mode.

When adding a new game mode at least the following aspects need to be considered:
1. the problem of having too many game modes
2. does the game mode provide sufficient added value to justify 1.)

Also it needs to be clarified why no-armor or no-akimbo, etc. might be an actual need. If there is an underlying problem in the existing game mode(s) then that should be researched to see if the root cause of the problem can be rectified.

I am closing this for now.

**Closed by drian0** 2021-05-11 06:26 UTC
Labels: Feature request
