### ISSUE TITLE
[release_1.3_alpha1] HUD gun-sway fails to pause at intermission

### ISSUE THREAD

**Issue by rpaladin** [assaultcube/AC#271] opened 2021-04-23 20:30 UTC
Current HUD item's sway motion fails to stop at the end of the game round.

**Comment by drian0** [comment] 2021-04-25 04:30
Thank you very much. I was able to reproduce this issue.

**Comment by drian0** [comment] 2021-05-05 07:28
Thank you. This has been resolved.

**Comment by drian0** [comment] 2021-11-06 19:37
This issue happens again in BETA3.

**Comment by RandomPandaStudios** [comment] 2021-12-25 02:55
I wonder if something simple like this would work even:
```
start_intermission = [ nosway 1 ]
```

**Comment by flowtron** [comment] 2022-05-09 11:03
Since we now move to the VANTAGE POINT of the map for intermission there's also no hudgun being rendered. Closing.

**Closed by flowtron** 2022-05-09 11:03 UTC
Labels: Bugfix request
