### ISSUE TITLE
[release_1.3_alpha1] Add back lightscale

### ISSUE THREAD

**Issue by elmillion** [assaultcube/AC#285] opened 2021-04-27 21:09 UTC
At the moment it's difficult to make the game brighter, especially when you record/stream your game. `/gamma` isn't very effective, the `/lightscale` command was a good solution, but it's not possible to use it anymore in 1.3 alpha.

I don't see much drawback to adding it back, everyone can use it, and it will ease the life of people streaming tournament.

With default lightscale on 1.3 alpha :
![image](https://user-images.githubusercontent.com/83298586/116312999-7a6bd480-a7ad-11eb-87a3-a768a1bd6193.png)

With lightscale 1 on 1.2 :
![image](https://user-images.githubusercontent.com/83298586/116312975-6fb13f80-a7ad-11eb-8a71-283a3332b1ff.png)

As you can see there is clearly a huge difference !

**Comment by drian0** [comment] 2021-04-28 07:35
Thank you very much for reporting this. 

Questions to clarify:
1) Is the observation correct that AC is too dark on most devices? Too dark means "can not see enemy well". I can confirm this from my side (tested with 2 notebooks) but we need to check this with more players and their devices.
2) Why did this happen in the first place? Were the first four AC maps too dark, then everyone tuned their gamma settings, and based with that new gamma setting new maps were created in the same dark fashion? Or are there other reasons why we got here?
3) Lightscale and gamma break the color range and make maps more ugly as the contrasts are either to weak or too strong. How else could we fix this reliably?

**Comment by cf-1984** [comment] 2021-04-28 15:28
1. Short answer: Yes. However, AC is probably perceived 'darker' than it is, due to the mostly high saturated and 'busy' textures used. For instance, swap the rather dark brown brick texture in ac_desert3 (see screenshots) with a light brown plastering texture and visibility will be enhanced significantly, while not changing the lighting itself.

2. I guess it's mostly caused by artistic choices. Generally maps look better with strong contrasts and gloomy areas from a aesthetic point of view. During mapping it is likely to be overlooked that thereby areas remain too dark for actual play, let alone competitive scenarios. Mappers using tuned gamma settings while editing surely could be another reason. Generally speaking, I think little thought has gone into most AC maps so far concerning visibility issues, especially considering competitive play. I personally only started to actively consider those aspects with ac_strand (created last year) for example.

3.  Gamma is the standard feature to adjust brightness on differently calibrated/configured display hardware. That should work for most cases. The issue that some players (myself included) couldn't change gamma setting in v1.2 anymore seems to be fixed with upgrading the SDL lib.
Though, I can imagine in screen capturing/streaming situations gamma  might not be the best solution. Lightscale is a weird feature, which according to the help text was meant to accompany fullbright, so presumably was intended only to work in edit mode. However, doesn't seem to do what the text says when fullbright is enabled. I personally don't understand the parameters of lightscale and how it changes light entities.
Maybe lightscale could work like a temporary scalelights (editing command to change all light entities at once), with one parameter for radius and one for intensity. Both values would need to be limited to reasonable values (like max +25% radius and +50% intensity), in order to maintain a minimum or artistic integrity and not to put users preferring the standard settings at a (significant) disadvantage, i.e. basically enabling fullbright outside edit mode.
It might require a certain algorithm to calculate the intensity for coloured lights to scale properly, though not sure about that. If a recalc would still be needed it should be performed automatically (needs to be called manually currently) and there should be an easy way to reset those changes (like /lightscale 0 0 or /resetlightscale).

**Comment by drian0** [comment] 2021-04-29 04:03
Ok, couple of more questions:

- Does gamma work in v1.3 just for you or does it also work for other players? That be interesting to know.
- If gamma works in v1.3, why would there still be a need for lightscale (for non-mappers)?
- How do we make sure that AC works "out of the box" for new players? Do we set a new, higher gamma-value by default?

I think that the proper fix would be to re-light the maps manually. I am fully aware that this is expensive in terms of effort. But it would yield the best results.

**Comment by cf-1984** [comment] 2021-04-29 11:39
1. We would have to get more people answering this, who also suffer from the gamma issue within v1.2 to verify it's gone with v1.3. Ultimately I can only speak for myself, so this would require broader testing. :)

2. This probably should be answered by the issue author. I just thought about how AC looks on Youtube videos or streams compared to other games. Most of the modern games being streamed come with highly saturated and bright colours. Compared to those AC indeed looks kind of flat/dull, that is, not very much engaging to watch. Though, this might be something that is taken care of in streaming/GPU software already. Hence, no need to build it into the game in the first place.

3. I certainly would opt for re-lighting the official maps manually. With the new editing possibilities this shouldn't become too expensive. Remains the question, what is the 'right' brightness? It would really help to get feedback from players regarding this. Anything from 'map A is just about perfectly bright overall', or 'map B has this spot being too dark, map C has this' and so on.

**Comment by AC-Panda** [comment] 2021-04-29 17:12
> Does gamma work in v1.3 just for you or does it also work for other players? That be interesting to know.

As I've stated to others, it works for me, and I was one of many who received the "gamma ramp manipulation not supported error" when connected to an duel-monitor that doesn't support the necessary drivers.

> If gamma works in v1.3, why would there still be a need for lightscale (for non-mappers)?

I totally agree, I don't think we need it now, what with gamma released. I think mappers can also set individual gammas on created maps now in 1.3? (might be inaccurate information on my part)

> How do we make sure that AC works "out of the box" for new players? Do we set a new, higher gamma-value by default?

I think it would help first impressions of AC a lot. FPS gamers tend to like bright environments (unless their fighting horror monsters). It would probably make more sense if environments were bright enough to even see their surroundings. They might not even learn about the `/gamma` function until after they stop playing AC!

**Comment by drian0** [comment] 2021-05-01 11:01
Ok, so this leaves us basically with two options:

* Manually re-light the official maps
* Add "brightness" to the initial setup screen so people won't miss it - plus unclutter that screen so that there are fewer options (see /showmenu "QUICK setup")

The first one will yield better results. The latter one will be quicker to implement.

I'll add Halo and Floppy to the loop.

**Comment by cf-1984** [comment] 2021-05-01 14:52
I think we need both. Gamma on the quick setup makes perfectly sense imo, as it introduces new players to this basic yet important setting right off the bat. Nonetheless, all official maps should come with a consistent of lighting/visibility which should work in any scenario even with gamma set 100. I'm wondering if we should revisit some fog settings as well. I certainly would like to change the fog on ac_werk.

**Comment by drian0** [comment] 2021-05-05 07:08
Comment from Halo:

> I would be for adding back light scale. I know a lot of people use it to see better as it works more naturally than gamma
> No need to relight maps of lightscale and gamma both are there

**Comment by BrutalSystem** [comment] 2021-05-05 19:54
gamma is horrible, not a good option.

![sent me this bug with gamma yesterday](https://user-images.githubusercontent.com/7694535/117200966-7a2d9380-adc2-11eb-8214-744248d62683.jpg)
sent me this bug with gamma yesterday.

lightscale should be maintained for v1.3, but I don’t see any need for players to choose a very high lighscale, lightscale 2 I think is an excellent standard, so essence of some parts of the maps is not entirely lost, lightscale 1 muddle your own crosshair because the crosshairs are white.

best option is to redo lighting of the maps in the future.

**Comment by drian0** [comment] 2021-05-07 07:37
-  'lightscale' as been added back (scope of this issue)
- 'gamma' is shown on the initial setup screen (#292)
- proper solution added to the backlog (#312)

**Closed by drian0** 2021-05-07 07:37 UTC
Labels: Change Request
