### ISSUE TITLE
GUI Scaling issues when using a ultrawide display 21:9 (3440 x 1440) 

### ISSUE THREAD

**Issue by Naqikhan** [assaultcube/AC#305] opened 2021-05-06 08:45 UTC
The game will not show HUD such as the mini map and what guns you are using. They can be seen at the corner of the screen.

![Picture1](https://user-images.githubusercontent.com/44385168/117268837-52b7e480-ae1d-11eb-867d-5d87bcc57f93.png)

**Comment by drian0** [comment] 2021-05-11 07:13
Unfortunately I could not reproduce this on my end with AC v1.3 ALPHA-2.

Steps:
- Start AC
- Navigate to settings > video settings
- Untick "Fullscreen"
- Set resolution to 114x380
- Apply changes

Actual result:
![image](https://user-images.githubusercontent.com/78469463/117773690-e849de80-b238-11eb-9d0b-e7926b0a4361.png)

What steps do I need to take to reproduce this?

**Comment by BrutalSystem** [comment] 2021-07-13 02:10
I don't have a problem with that, but the hud can be upgraded for larger screen/use of more than one screen. 
![20210713_02 03 18_ac_desert3_CTF](https://user-images.githubusercontent.com/7694535/125378984-172e1f00-e366-11eb-9fa4-f0c9e39dd2da.jpg)
i used two screen to get the resolution, and i used nvdia panel to configure two screen.

**Comment by drian0** [comment] 2021-07-13 08:40
I am closing this issue since it can not be reproduced.
If there is new information available on how to reproduce this issue we an reopen it.

**Closed by drian0** 2021-07-13 08:40 UTC
Labels: Bugfix request
