### ISSUE TITLE
[release_1.3_alpha1 Mac version] impossible to shoot

### ISSUE THREAD

**Issue by ketarXVII** [assaultcube/AC#300] opened 2021-05-03 16:48 UTC
I can't shoot. Pressing left-click button freeze everything. 
Only once, when trying, suddenly the window changed size and I could shoot.

**Comment by ketarXVII** [comment] 2021-05-03 16:51
I must probably add that I am using MacOS High Sierra 10.13.6

**Comment by RonaldReagan** [comment] 2021-05-10 03:56
I experienced this today and believe it is an intermittent issue that is related to the mouse grabbing behavior. Specifically I think it is an issue where the mouse is on the top bar of window or some other piece of the chrome.

@ketarXVII  can you see if you can replicate this issue? If so can you:

1. Check if the game freezes when you push down the mouse button
2. If the issue is fixed by tabbing out and back into the game (maybe need to move the mouse around in the middle)

**Comment by ketarXVII** [comment] 2021-05-10 08:38
Well actually it happens always, it is not a random bug. So yeah I can replicate it :) I also tried it on another mac with the latest OS (11.13.2) and the issue is there (using both mouse and trackpad).  
The game itself freeze, if I shoot and walk/run at the same time I can hear the sound of my own steps in the background, but everything is frozen. When I stop shooting tho I find my player in a new position (so I was in reality moving).

I tried tab out: I succeeded once and in that case I was able to shoot. But then every time I tried again I was not able to tab out since the cursor was locked inside the perimeter of the AC window: I literally could not move it on the desktop or on another application.

**Comment by ketarXVII** [comment] 2021-05-10 09:02
I also tried to d/load the latest alpha-2 on a different older Mac  (sporting El Capitan OS 10.11.6) but it doesn't recognize the disk image when unzipping the.dmg

**Comment by RonaldReagan** [comment] 2021-05-10 12:26
@ketarXVII Sounds good, I was able to replicate the issue _once_. Not sure why I can't reliably replicate it like you can. Are. you running in fullscreen or windowed?

After poking around I see that there is a variable relativemouse that changes the mouse grab behavior. Can you run /relativemouse and make sure it starts out with the default of 1, and then try changing it to /relativemouse 0? After you run that you will have to tab out and back in again for the changes to take effect.

**Comment by ketarXVII** [comment] 2021-05-10 13:11
Ok I tried a few times. It is related to /relativemouse. It says the def is 1. When in 1 it gives the issue, when in 0 not. Also when in 1 I can't tab out from AC.

**Comment by ketarXVII** [comment] 2021-05-11 05:55
@RonaldReagan yes I will. But what is /relativemouse suppose to do? It would be useful to know, just to get an idea of what I could expect.

**Comment by RonaldReagan** [comment] 2021-05-11 12:02
@ketarXVII It changes what mechanism is used to trap the mouse and provide feedback to the client on how much someone moved the mouse. I'm going out on a limb here because I'm not 100% sure but I believe instead of having SDL handle it all this does more of the work itself.

**Comment by RonaldReagan** [comment] 2021-05-12 03:35
I've found a way to replicate. When starting AC if I have my cursor on the far left side of the window, it will create the issue.

Adding this line appears to fix it. See https://wiki.libsdl.org/SDL_HINT_MOUSE_RELATIVE_MODE_WARP for documentation.
`SDL_SetHintWithPriority(SDL_HINT_MOUSE_RELATIVE_MODE_WARP, "1", SDL_HINT_OVERRIDE);`

I'm researching if this is the best way to fix it and if it should be OSX specific or applied to the other OS's

**Comment by RonaldReagan** [comment] 2021-05-25 00:03
@ketarXVII this has been incorporated in the latest beta. Could you verify its been fixed for you?

**Comment by ketarXVII** [comment] 2021-05-25 10:57
Yes. Fixed.

**Closed** 2021-05-25 11:09 UTC
Labels: Bugfix request, MacOS
